language: scala
sudo: false
scala:
   - 2.11.12
   - 2.12.10
   - 2.13.2

jdk:
   - openjdk8
   - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
